import { Metadata } from "next";

import RootLayoutClient from "./RootLayoutClient"; // Client component with providers
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "SyncUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute={"class"} defaultTheme={"dark"}>
          <RootLayoutClient>{children}</RootLayoutClient>
        </ThemeProvider>
      </body>
    </html>
  );
}
