apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication
  template:
    metadata:
      labels:
        app: communication
    spec:
      containers:
        - name: communication
          image: ajfer/syncup-comm-service
          resources:
            requests:
              memory: "256Mi" # Increased request to match previous limit
              cpu: "250m"
            limits:
              memory: "512Mi" # Doubled the limit
              cpu: "500m"
          env:
            - name: PORT
              value: "3004"
---
apiVersion: v1
kind: Service
metadata:
  name: communication-clusterid-service
spec:
  ports:
    - port: 3004
      targetPort: 3004
  selector:
    app: communication
