apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv-syncup
  namespace: syncup
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://syncup.mhdajfer.in"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/websocket-services: "communication-clusterid-service"
spec:
  tls:
    - hosts:
        - syncup.mhdajfer.in
      secretName: letsencrypt-nginx
  ingressClassName: nginx
  rules:
    - host: syncup.mhdajfer.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-nodeport-srv
                port:
                  number: 3000
          - path: /users/
            pathType: Prefix
            backend:
              service:
                name: user-clusterid-service
                port:
                  number: 3003
          - path: /projects/
            pathType: Prefix
            backend:
              service:
                name: project-clusterid-service
                port:
                  number: 3002
          - path: /comm/
            pathType: Prefix
            backend:
              service:
                name: communication-clusterid-service
                port:
                  number: 3004
          - path: /tenants/
            pathType: Prefix
            backend:
              service:
                name: tenant-clusterid-service
                port:
                  number: 3005
