apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  namespace: syncup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: ajfer/syncup-project-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "3002"
            - name: DB_URL
              value: "mongodb+srv://ajferaju9961:Achuaju6@cluster.p3idumj.mongodb.net/syncUp-project-service"
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: project-clusterid-service
  namespace: syncup
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: project
