apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant
  namespace: syncup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  template:
    metadata:
      labels:
        app: tenant
    spec:
      containers:
        - name: tenant
          image: ajfer/syncup-tenant-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "3005"
            - name: DB_URL
              value: "mongodb+srv://ajferaju9961:Achuaju6@cluster.p3idumj.mongodb.net/syncUp-tenant-service"
          envFrom:
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: tenant-clusterid-service
  namespace: syncup
spec:
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    app: tenant
