name: tenant-deploy

on:
  push:
    branches:
      - main
    paths:
      - "backend/Tenant_Service/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: cd backend/Tenant_Service && docker build -t syncup/tenant-service .

      - name: tag Docker image
        run: docker tag syncup/tenant-service ajfer/syncup-tenant-service

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ajfer/syncup-tenant-service

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save Kubernetes config
        run: doctl kubernetes cluster kubeconfig save syncup

      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment tenant -n syncup
